name: app_client
description: ShipIt Golden App - Serverpod generated client
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.12.2

resolution: workspace

dependencies:
  serverpod_client: 3.4.13
  serverpod_auth_core_client: 3.4.13
  serverpod_auth_idp_client: 3.4.13
  serverpod_serialization: 3.4.13

dev_dependencies:
  build_runner: ^2.4.0
  test: ^1.25.0